target:	SoloSolitaire2

SoloS_lib:	SoloSolitaire2_lib.hpp SoloSolitaire2.cpp
			g++ -std=c++11 -c SoloSolitaire2.cpp


SoloS_game: SoloSolitaire2
		g++ SoloSolitaire2.o -o SoloSolitaire2

clean:
		rm SoloSolitaire2
